# Generated by Django 2.0.6 on 2018-10-09 16:50

from django.db import migrations, models
import libs.core.media.api.fields.RemoteFileField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(null=True)),
                ('file', libs.core.media.api.fields.RemoteFileField.RemoteFileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medias',
                'permissions': (('list_medias', 'Can list medias'),),
            },
        ),
    ]
