# Generated by Django 2.1.4 on 2018-12-22 19:17

import dirtyfields.dirtyfields
from django.db import migrations, models
import libs.core.media.api.fields.RemoteFileField
import libs.core.media.api.models.Media
import libs.core.media.api.storage.ChunkFileStorage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webdjango', '0002_auto_20181222_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alt', models.CharField(max_length=255, null=True)),
                ('file', libs.core.media.api.fields.RemoteFileField.RemoteFileField(blank=True, null=True, storage=libs.core.media.api.storage.ChunkFileStorage.ChunkFileStorage(), upload_to=libs.core.media.api.models.Media.media_path)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('extension', models.CharField(blank=True, max_length=16, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('current_chunk', models.IntegerField(blank=True, default=None, null=True)),
                ('total_chunks', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'medias',
                'ordering': ['-created'],
                'permissions': (('download_media', 'Can Download Media'),),
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
