# Generated by Django 2.1.7 on 2019-06-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='storage_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
