# Generated by Django 2.0.6 on 2018-11-26 12:17

from django.db import migrations, models
import libs.core.media.api.fields.RemoteFileField
import libs.core.media.api.models.Media
import libs.core.media.api.storage.ChunkFileStorage


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-id'], 'permissions': (('list_medias', 'Can list medias'), ('view_media', 'Can view media'), ('download_medi', 'Can Download Media'))},
        ),
        migrations.AddField(
            model_name='media',
            name='bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='content_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='current_chunk',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='extension',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='total_chunks',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='alt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=libs.core.media.api.fields.RemoteFileField.RemoteFileField(blank=True, null=True, storage=libs.core.media.api.storage.ChunkFileStorage.ChunkFileStorage(), upload_to=libs.core.media.api.models.Media.media_path),
        ),
    ]
