# Generated by Django 2.1.7 on 2019-06-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_storage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_secure',
            field=models.BooleanField(default=False),
        ),
    ]
