# Generated by Django 2.0.6 on 2018-11-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20181126_1017'),
        ('media', '0002_auto_20181122_1458'),
    ]

    operations = [
    ]
