# Generated by Django 2.1.4 on 2018-12-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_merge_20181128_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-id'], 'permissions': (('download_media', 'Can Download Media'),)},
        ),
    ]
