# Generated by Django 2.1.4 on 2018-12-23 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import webdjango.models.TranslationModel


def init_migrations(apps, schema_editor):
    from libs.core.cms.api.models.Page import Page
    from libs.core.cms.api.models.Block import Block
    from libs.core.cms.api.configs import CMSCoreConfig
    from webdjango.models.Core import CoreConfig, Website
    from webdjango.configs import CONFIG_HOME_PAGE, DEFAULT_FOOTER, DEFAULT_HEADER

    website = Website.objects.create(
        domain="http://localhost:4200/", code='default')

    header = Block.objects.create(
        title="Header", slug="header", content="<nav>Header</nav>")
    footer = Block.objects.create(
        title="Footer", slug="footer", content="<footer>Footer</footer>")

    page = Page.objects.create(
        title="Home", slug="Home", content="<h1>Hello World!</h1>", header=header, footer=footer)



    CoreConfig.write(CMSCoreConfig.GROUP_SLUG, {
                     CONFIG_HOME_PAGE: page.pk, DEFAULT_FOOTER: footer.pk, DEFAULT_HEADER: header.pk}, website=website)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webdjango', '0002_auto_20181222_2028'),

    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_block',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('wrapper_class', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_menu',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('alt', models.CharField(max_length=255)),
                ('target', models.CharField(choices=[('_blank', '_blank'), ('_self', '_self'), ('_parent', '_parent'), ('_top', '_top')], default='_self', max_length=255)),
                ('position', models.PositiveSmallIntegerField()),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='cms.Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.MenuItem')),
            ],
            options={
                'db_table': 'cms_menu_item',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('language', models.CharField(default=webdjango.models.TranslationModel.default_i18n, max_length=5, validators=[webdjango.models.TranslationModel.validate_i18n])),
                ('translation', django_mysql.models.JSONField(default=None, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('footer', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='footers', to='cms.Block')),
                ('header', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='headers', to='cms.Block')),
            ],
            options={
                'db_table': 'cms_page',
                'ordering': ['-created'],
            },
        ),
        migrations.RunPython(init_migrations)
    ]
