# Generated by Django 2.1.4 on 2019-01-18 21:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190102_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='opengraph',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='twitter',
            field=django_mysql.models.JSONField(default=None, null=True),
        ),
    ]
