# Generated by Django 2.0.6 on 2018-11-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180918_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id'], 'permissions': (('list_pages', 'Can list pages'),)},
        ),
        migrations.AlterModelTable(
            name='page',
            table='cms_page',
        ),
    ]
