# Generated by Django 2.0.6 on 2018-11-26 17:56

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import libs.core.cms.api.models.Menu

def set_default_header_footer(apps, schema_editor):
    from libs.core.cms.api.models.Page import Page
    from libs.core.cms.api.models.Block import Block

    header = Block.objects.create(title="Header", slug="header", content="<nav>HEADER</nav>")
    footer = Block.objects.create(title="Footer", slug="footer", content="<footer>Footer</footer>")
    pages = Page.objects.all()
    for page in pages:
        page.header = header
        page.footer = footer
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180918_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_block',
                'ordering': ['-id'],
                'permissions': (('list_blocks', 'Can list blocks'),),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('wrapper_class', models.CharField(max_length=255)),
                ('items', djongo.models.fields.ArrayModelField(model_container=libs.core.cms.api.models.Menu.MenuItem)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_menu',
                'ordering': ['-id'],
                'permissions': (('list_menus', 'Can list menus'),),
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id'], 'permissions': (('list_pages', 'Can list pages'),)},
        ),
        migrations.AlterModelTable(
            name='page',
            table='cms_page',
        ),
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='footers', to='cms.Block'),
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='headers', to='cms.Block'),
        ),
        migrations.RunPython(set_default_header_footer)
    ]
