# Generated by Django 2.0.6 on 2018-11-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20181126_1556'),
        ('cms', '0006_auto_20181122_1458'),
    ]

    operations = [
    ]
