# Generated by Django 2.1.4 on 2019-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20190122_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='cms.PageCategory'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='pages', to='cms.PageTag'),
        ),
    ]
