# Generated by Django 2.0.6 on 2018-11-28 21:34

import django.core.validators
from django.db import migrations, models
import djongo.models.json
import webdjango.models.AbstractModels


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_merge_20181128_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(default=webdjango.models.AbstractModels.default_i18n, max_length=5, validators=[webdjango.models.AbstractModels.validate_i18n]),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)]),
        ),
        migrations.AddField(
            model_name='page',
            name='translation',
            field=djongo.models.json.JSONField(default=None, null=True),
        ),
    ]
