# Generated by Django 2.1.4 on 2018-12-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20181128_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-id']},
        ),
    ]
