# Generated by Django 2.1.4 on 2019-01-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(related_name='pages', to='cms.PageCategory'),
        ),
        migrations.AlterField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='footers', to='cms.Block'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headers', to='cms.Block'),
        ),
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(related_name='pages', to='cms.PageTag'),
        ),
    ]
