# Generated by Django 2.1.4 on 2019-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20190221_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
