# Generated by Django 2.1.4 on 2019-02-28 14:00

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_menuitem_css_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('show_title', models.BooleanField(default=True)),
                ('clear_complete', models.BooleanField(default=True)),
                ('hide_complete', models.BooleanField(default=True)),
                ('fields', django_mysql.models.JSONField(blank=True, default=None, null=True)),
                ('actions', django_mysql.models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSubmition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', django_mysql.models.JSONField(default=dict)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitions', to='cms.Form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
