# Generated by Django 2.1.4 on 2019-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_form_formaction_formfield_formsubmition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formaction',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='formfield',
            name='element_class',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='placeholder',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='wrapper_class',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label_position',
            field=models.CharField(choices=[('above', 'above'), ('below', 'below')], default='above', max_length=255),
        ),
    ]
