# Generated by Django 2.1.7 on 2019-03-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190313_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('textArea', 'Text Area'), ('select', 'Select'), ('ngSelect', 'NG Select'), ('codeEditor', 'CodeEditor')], default='text', max_length=255),
        ),
    ]
