# Generated by Django 2.1.7 on 2019-03-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20190316_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='alt',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
