# Generated by Django 2.1.7 on 2019-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20190321_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('textArea', 'Text Area'), ('select', 'Select'), ('ngSelect', 'NG Select'), ('codeEditor', 'CodeEditor'), ('label', 'Label'), ('switch', 'Switch (ON/OFF)'), ('checkbox', 'Checkbox')], default='text', max_length=255),
        ),
    ]
