# Generated by Django 2.1.4 on 2018-12-13 13:56

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import libs.plugins.provider.api.models.City


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(default=None, max_length=255, null=True)),
                ('code', models.SlugField(default=None, null=True)),
                ('postal_codes', djongo.models.fields.ArrayModelField(default=None, model_container=libs.plugins.provider.api.models.City.NumberRange, model_form_class=libs.plugins.provider.api.models.City.NumberRangeForm, null=True)),
                ('streets', djongo.models.fields.ArrayModelField(default=None, model_container=libs.plugins.provider.api.models.City.Streets, model_form_class=libs.plugins.provider.api.models.City.StreetsForm, null=True)),
            ],
            options={
                'db_table': 'provider_city',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PageRedirect',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cities', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='redirect', to='provider.City')),
                ('default_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_default', to='cms.Page')),
                ('redirect_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_redirect', to='cms.Page')),
            ],
            options={
                'db_table': 'provider_redirect',
                'ordering': ['-created'],
            },
        ),
    ]
