# Generated by Django 2.1.4 on 2018-12-13 16:52

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import libs.core.media.api.fields.RemoteFileField
import libs.core.media.api.models.Media
import libs.core.media.api.storage.ChunkFileStorage


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', libs.core.media.api.fields.RemoteFileField.RemoteFileField(blank=True, null=True, storage=libs.core.media.api.storage.ChunkFileStorage.ChunkFileStorage(), upload_to=libs.core.media.api.models.Media.media_path)),
                ('groups', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=255)),
                ('number', models.FloatField()),
                ('position', models.IntegerField()),
                ('products', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='store.Product')),
            ],
            options={
                'abstract': False,
                'db_table': 'provider_channel',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condos', to='provider.City')),
                ('products', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.SET_NULL, related_name='condos', to='store.Product')),
            ],
            options={
                'abstract': False,
                'db_table': 'provider_condo',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('orders', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.SET_NULL, related_name='resellers', to='store.Order')),
            ],
            options={
                'abstract': False,
                'db_table': 'provider_reseller',
                'ordering': ['-created'],
            },
        ),
    ]
