# Generated by Django 2.1.4 on 2018-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20181226_1521'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='products',
        ),
        migrations.AddField(
            model_name='channel',
            name='products',
            field=models.ManyToManyField(related_name='channels', to='store.Product'),
        ),
    ]
