# Generated by Django 2.1.4 on 2018-12-22 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageredirect',
            name='cities',
        ),
        migrations.AddField(
            model_name='pageredirect',
            name='cities',
            field=models.ManyToManyField(to='provider.City'),
        ),
        migrations.AlterField(
            model_name='pageredirect',
            name='default_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_default', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='pageredirect',
            name='redirect_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_redirect', to='cms.Page'),
        ),
    ]
