# Generated by Django 2.1.4 on 2018-12-10 14:07

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20181209_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageredirect',
            name='cities',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirect', to='provider.City'),
        ),
    ]
