# Generated by Django 2.1.4 on 2019-01-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_orderline'),
        ('provider', '0005_city_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('is_condo', models.BooleanField()),
                ('products', models.ManyToManyField(related_name='plan_types', to='store.Product')),
            ],
            options={
                'db_table': 'provider_plan_type',
                'ordering': ['-created'],
            },
        ),
    ]
