# Generated by Django 2.1.4 on 2019-01-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_plantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantype',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='is_condo',
            field=models.BooleanField(default=False),
        ),
    ]
