# Generated by Django 2.1.4 on 2019-01-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20190129_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantype',
            options={'ordering': ['position']},
        ),
    ]
