# Generated by Django 2.1.4 on 2019-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_order_token'),
        ('provider', '0008_auto_20190130_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='orders',
            field=models.ManyToManyField(related_name='resellers', to='store.Order'),
        ),
    ]
