# Generated by Django 2.1.7 on 2019-03-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_reseller_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
