# Generated by Django 2.1.7 on 2019-03-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_plantype_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='condo',
            options={'ordering': ['-name']},
        ),
    ]
