# Generated by Django 2.1.7 on 2019-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20190327_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
