# Generated by Django 2.1.7 on 2019-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_city_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='taxvat',
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True),
        ),
    ]
