# Generated by Django 2.1.7 on 2019-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_reseller_taxvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseller',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reseller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
