# Generated by Django 2.0.6 on 2018-09-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0002_auto_20180921_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Plugin',
        ),
        migrations.AlterModelTable(
            name='plugin',
            table='core_plugins',
        ),
    ]
