# Generated by Django 2.0.6 on 2018-09-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0003_auto_20180921_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='angular_module',
            field=models.CharField(default='DefaultModule', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='parent_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='webdjango.Theme'),
        ),
    ]
