# Generated by Django 2.1.4 on 2019-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0004_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
