# Generated by Django 2.1.4 on 2019-01-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0005_auto_20190130_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=12),
        ),
    ]
