# Generated by Django 2.0.6 on 2018-09-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0005_auto_20180921_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'permissions': (('list_core_website', 'Can list core_website'),)},
        ),
        migrations.AlterField(
            model_name='plugin',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='webdjango.Author'),
        ),
        migrations.AlterModelTable(
            name='website',
            table='core_website',
        ),
    ]
