# Generated by Django 2.1.4 on 2019-02-01 13:24

from django.db import migrations, models
import django_mysql.models
import webdjango.models.TranslationModel


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0006_website_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default=webdjango.models.TranslationModel.default_i18n, max_length=5, validators=[webdjango.models.TranslationModel.validate_i18n])),
                ('translation', django_mysql.models.JSONField(default=None, null=True)),
                ('subject', models.CharField(default='Label', max_length=255)),
                ('code', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
