# Generated by Django 2.0.6 on 2018-09-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0006_auto_20180922_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('list_core_author', 'Can list core_author'),)},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'permissions': (('list_core_plugin', 'Can list core_plugin'),)},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'permissions': (('list_core_theme', 'Can list core_theme'),)},
        ),
        migrations.AlterModelTable(
            name='plugin',
            table='core_plugin',
        ),
    ]
