# Generated by Django 2.1.4 on 2019-02-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0007_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created']},
        ),
    ]
