# Generated by Django 2.0.6 on 2018-11-26 12:17

from django.db import migrations
import djongo.models.json


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0007_auto_20180922_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'permissions': (('list_core_author', 'Can list core_author'),)},
        ),
        migrations.AlterModelOptions(
            name='coreconfig',
            options={'ordering': ['-id'], 'permissions': (('list_core_config', 'Can list core_config'),)},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['-id'], 'permissions': (('list_core_plugin', 'Can list core_plugin'),)},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-id'], 'permissions': (('list_core_theme', 'Can list core_theme'),)},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-id'], 'permissions': (('list_core_website', 'Can list core_website'),)},
        ),
        migrations.AlterField(
            model_name='coreconfig',
            name='value',
            field=djongo.models.json.JSONField(max_length=500, null=True),
        ),
    ]
