# Generated by Django 2.1.4 on 2019-02-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0008_auto_20190214_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCoreConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
