# Generated by Django 2.1.4 on 2018-12-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0009_merge_20181128_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='coreconfig',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['-id']},
        ),
    ]
