# Generated by Django 2.1.4 on 2019-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0009_emailcoreconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcoreconfig',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
