# Generated by Django 2.1.7 on 2019-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0010_auto_20190221_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreconfig',
            name='secure',
            field=models.BooleanField(default=False),
        ),
    ]
