# Generated by Django 2.0.6 on 2018-09-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20180912_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
