# Generated by Django 2.1.4 on 2018-12-13 13:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import django_prices.models
import djongo.models.fields
import djongo.models.json
import libs.core.utils.api.models.Address
import libs.core.utils.api.money
import libs.core.utils.api.weight
import libs.plugins.store.api.models.Cart
import libs.plugins.store.api.models.Payment
import libs.plugins.store.api.models.Product
import measurement.measures.mass
import uuid
import webdjango.fields.MongoFields
import webdjango.models.TranslationModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('billing_address', djongo.models.fields.EmbeddedModelField(blank=True, model_container=libs.core.utils.api.models.Address.Address, null=True)),
                ('shipping_address', djongo.models.fields.EmbeddedModelField(blank=True, model_container=libs.core.utils.api.models.Address.Address, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('discount_amount', django_prices.models.MoneyField(currency='USD', decimal_places=2, default=libs.core.utils.api.money.zero_money, max_digits=12)),
                ('discount_name', models.CharField(blank=True, max_length=255, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=12, null=True)),
                ('items', djongo.models.fields.ArrayModelField(model_container=libs.plugins.store.api.models.Cart.CartItem)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_num', models.CharField(editable=False, max_length=36)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='draft', max_length=32)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gateway', models.CharField(max_length=255)),
                ('charge_status', models.CharField(choices=[('charged', 'Charged'), ('not-charged', 'Not-charged'), ('refunded', 'Refunded')], default='not-charged', max_length=15)),
                ('billing_address', djongo.models.fields.EmbeddedModelField(blank=True, model_container=libs.core.utils.api.models.Address.Address, null=True)),
                ('customer_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', djongo.models.json.JSONField()),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('cc_last_digits', models.CharField(blank=True, default='', max_length=4)),
                ('cc_brand', models.CharField(blank=True, default='', max_length=40)),
                ('cc_exp_month', models.PositiveIntegerField(blank=True, null=True)),
                ('cc_exp_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default=webdjango.models.TranslationModel.default_i18n, max_length=5, validators=[webdjango.models.TranslationModel.validate_i18n])),
                ('translation', djongo.models.json.JSONField(default=None, null=True)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('available_on', models.DateTimeField(blank=True, null=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=Decimal('1'))),
                ('quantity_allocated', models.IntegerField(default=Decimal('0'))),
                ('cost', webdjango.fields.MongoFields.MongoDecimalField(decimal_places=2, max_digits=12)),
                ('pricing', djongo.models.fields.EmbeddedModelField(model_container=libs.plugins.store.api.models.Product.ProductPricing, null=True)),
                ('attributes', djongo.models.json.JSONField(blank=True, default=None, null=True)),
                ('product_class', models.CharField(choices=[('simple', 'simple'), ('variant', 'variant'), ('bundle', 'bundle')], default='simple', max_length=32)),
                ('variants', djongo.models.fields.ArrayModelField(blank=True, default=None, model_container=libs.plugins.store.api.models.Product.BaseProduct, null=True)),
                ('variant_attributes', djongo.models.json.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=256)),
                ('language', models.CharField(default=webdjango.models.TranslationModel.default_i18n, max_length=5, validators=[webdjango.models.TranslationModel.validate_i18n])),
                ('translation', djongo.models.json.JSONField(default=None, null=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_class', models.CharField(choices=[('simple', 'simple'), ('variant', 'variant'), ('bundle', 'bundle')], default='simple', max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('attributes', djongo.models.fields.ArrayModelField(blank=True, default=None, model_container=libs.plugins.store.api.models.Product.ProductAttribute, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping')], max_length=30)),
                ('price', django_prices.models.MoneyField(currency='USD', decimal_places=2, default=0, max_digits=12)),
                ('minimum_order_price', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, default=0, max_digits=12, null=True)),
                ('maximum_order_price', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True)),
                ('minimum_order_weight', django_measurement.models.MeasurementField(blank=True, default=libs.core.utils.api.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_order_weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('type', models.CharField(choices=[('auth', 'Authorization'), ('charge', 'Charge'), ('refund', 'Refund'), ('capture', 'Capture'), ('void', 'Void')], max_length=10)),
                ('status', models.CharField(choices=[('success', 'success'), ('error', 'error'), ('pending', 'pending')], max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=12)),
                ('error', models.CharField(choices=[(libs.plugins.store.api.models.Payment.TransactionError('declined'), 'declined'), (libs.plugins.store.api.models.Payment.TransactionError('expired'), 'expired'), (libs.plugins.store.api.models.Payment.TransactionError('incorrect_number'), 'incorrect_number'), (libs.plugins.store.api.models.Payment.TransactionError('incorrect_zip'), 'incorrect_zip'), (libs.plugins.store.api.models.Payment.TransactionError('incorrect_address'), 'incorrect_address'), (libs.plugins.store.api.models.Payment.TransactionError('incorrect_cvv'), 'incorrect_cvv'), (libs.plugins.store.api.models.Payment.TransactionError('invalid_number'), 'invalid_number'), (libs.plugins.store.api.models.Payment.TransactionError('invalid_cvv'), 'invalid_cvv'), (libs.plugins.store.api.models.Payment.TransactionError('invalid_expiry_date'), 'invalid_expiry_date'), (libs.plugins.store.api.models.Payment.TransactionError('processing_error'), 'processing_error')], max_length=256, null=True)),
                ('gateway_response', djongo.models.json.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('value', 'All products'), ('product', 'Specific products'), ('collection', 'Specific collections of products'), ('category', 'Specific categories of products'), ('shipping', 'Shipping')], default='value', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('used', models.PositiveIntegerField(default=0, editable=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('apply_once_per_order', models.BooleanField(default=False)),
                ('discount_value_type', models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_amount_spent', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='addons',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=None, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='products', to='store.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='bundle_products',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, related_name='bundles', to='store.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=djongo.models.fields.ArrayReferenceField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.ProductType'),
        ),
    ]
