# Generated by Django 2.1.4 on 2018-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('codeEditor', 'CodeEditor'), ('select', 'Select'), ('text', 'Text'), ('ckeditor', 'CkEditor'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
