# Generated by Django 2.1.4 on 2018-12-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('select', 'Select'), ('text', 'Text'), ('ckeditor', 'CkEditor'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
