# Generated by Django 2.1.4 on 2018-12-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181222_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='webdjango.Address'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('ckeditor', 'CkEditor'), ('select', 'Select'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
