# Generated by Django 2.1.4 on 2018-12-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181223_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='list',
            new_name='pricing_list',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='pricing_sale',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('text', 'Text'), ('codeEditor', 'CodeEditor'), ('select', 'Select'), ('button', 'Button'), ('ckeditor', 'CkEditor')], default='text', max_length=32),
        ),
    ]
