# Generated by Django 2.1.4 on 2018-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20181222_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('codeEditor', 'CodeEditor'), ('select', 'Select'), ('ckeditor', 'CkEditor'), ('button', 'Button'), ('text', 'Text')], default='text', max_length=32),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
