# Generated by Django 2.1.4 on 2018-12-26 15:55

from decimal import Decimal
from django.db import migrations, models
import django_measurement.models
import django_prices.models
import measurement.measures.mass
import webdjango.utils.weight


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20181226_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_sale',
            field=django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=Decimal('1'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_allocated',
            field=models.IntegerField(blank=True, default=Decimal('0'), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_depth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_height',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_width',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, default=webdjango.utils.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('ckeditor', 'CkEditor'), ('codeEditor', 'CodeEditor'), ('select', 'Select'), ('text', 'Text'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
