# Generated by Django 2.1.4 on 2018-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20181226_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('select', 'Select'), ('text', 'Text'), ('codeEditor', 'CodeEditor'), ('ckeditor', 'CkEditor')], default='text', max_length=32),
        ),
    ]
