# Generated by Django 2.1.4 on 2018-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20181226_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('button', 'Button'), ('codeEditor', 'CodeEditor'), ('ckeditor', 'CkEditor')], default='text', max_length=32),
        ),
    ]
