# Generated by Django 2.1.4 on 2018-12-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20181227_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('ckeditor', 'CkEditor'), ('codeEditor', 'CodeEditor'), ('select', 'Select')], default='text', max_length=32),
        ),
    ]
