# Generated by Django 2.1.4 on 2019-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20190118_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('text', 'Text'), ('select', 'Select'), ('codeEditor', 'CodeEditor'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
