# Generated by Django 2.1.4 on 2019-01-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190122_1432'),
        ('store', '0012_auto_20190122_1735'),
    ]

    operations = [
    ]
