# Generated by Django 2.1.4 on 2019-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_merge_20190122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('codeEditor', 'CodeEditor'), ('text', 'Text'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
