# Generated by Django 2.1.4 on 2019-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20190123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('text', 'Text'), ('button', 'Button'), ('select', 'Select'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
