# Generated by Django 2.1.4 on 2019-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190123_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrule',
            name='require_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='rule_type',
            field=models.CharField(choices=[('fixed', 'USD'), ('percentage', '%'), ('fee', 'USD')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogrule',
            name='rule_type',
            field=models.CharField(choices=[('fixed', 'USD'), ('percentage', '%'), ('fee', 'USD')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('codeEditor', 'CodeEditor'), ('button', 'Button'), ('text', 'Text')], default='text', max_length=32),
        ),
    ]
