# Generated by Django 2.1.4 on 2019-01-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20190125_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('button', 'Button'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
