# Generated by Django 2.1.4 on 2019-01-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20190125_1316'),
        ('store', '0016_auto_20190124_1635'),
    ]

    operations = [
    ]
