# Generated by Django 2.1.4 on 2019-01-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_merge_20190125_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=None, related_name='product', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='cartrule',
            name='rule_type',
            field=models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogrule',
            name='rule_type',
            field=models.CharField(choices=[('fixed', 'USD'), ('percentage', '%')], default='fixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('codeEditor', 'CodeEditor'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
