# Generated by Django 2.1.4 on 2019-01-27 02:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20190126_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartrule',
            name='item_conditions',
            field=django_mysql.models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('select', 'Select'), ('codeEditor', 'CodeEditor'), ('text', 'Text')], default='text', max_length=32),
        ),
    ]
