# Generated by Django 2.1.4 on 2019-01-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20190127_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('codeEditor', 'CodeEditor'), ('button', 'Button')], default='text', max_length=32),
        ),
    ]
