# Generated by Django 2.1.4 on 2019-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20190128_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartterm',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('codeEditor', 'CodeEditor'), ('text', 'Text'), ('button', 'Button'), ('select', 'Select')], default='text', max_length=32),
        ),
    ]
