# Generated by Django 2.1.4 on 2019-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20190128_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartterm',
            name='products',
        ),
        migrations.AddField(
            model_name='cartterm',
            name='products',
            field=models.ManyToManyField(related_name='terms', to='store.Product'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('select', 'Select'), ('button', 'Button'), ('text', 'Text'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
