# Generated by Django 2.1.4 on 2019-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20190128_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('select', 'Select'), ('codeEditor', 'CodeEditor')], default='text', max_length=32),
        ),
    ]
