# Generated by Django 2.1.4 on 2019-01-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20190129_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartterm',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='cart',
            name='user_email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254),
        ),
    ]
