# Generated by Django 2.1.4 on 2019-01-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20190129_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
