# Generated by Django 2.1.4 on 2019-01-29 03:24

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20190129_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=256)),
                ('product_sku', models.CharField(max_length=32)),
                ('is_shipping_required', models.BooleanField()),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_fulfilled', models.IntegerField(default=0)),
                ('unit_cost', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='cost')),
                ('unit_base_price', django_prices.models.MoneyField(currency='USD', decimal_places=2, max_digits=12, verbose_name='list')),
                ('unit_price', django_prices.models.MoneyField(blank=True, currency='USD', decimal_places=2, max_digits=12, null=True, verbose_name='sale')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='store.Order')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
