# Generated by Django 2.1.4 on 2019-01-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20190129_0122'),
        ('store', '0030_orderline'),
    ]

    operations = [
    ]
