# Generated by Django 2.1.4 on 2019-01-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_merge_20190129_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_email',
        ),
    ]
