# Generated by Django 2.1.4 on 2019-01-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_cart_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='token',
        ),
    ]
