# Generated by Django 2.1.4 on 2019-02-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0008_auto_20190214_1614'),
        ('store', '0033_remove_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET, related_name='order', to='webdjango.Website'),
        ),
    ]
