# Generated by Django 2.1.4 on 2019-02-14 18:21

from django.db import migrations
import django_mysql.models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='product_data',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderline',
            name='product_sku',
        ),
    ]
