# Generated by Django 2.1.4 on 2019-02-14 18:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_order_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreEmailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderline',
            name='data',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=None, related_name='order_line', to='store.Product'),
        ),
    ]
