# Generated by Django 2.1.7 on 2019-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20190316_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='class_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('textArea', 'Text Area'), ('select', 'Select'), ('ngSelect', 'NG Select'), ('codeEditor', 'CodeEditor'), ('label', 'Label')], default='text', max_length=32),
        ),
    ]
