# Generated by Django 2.1.7 on 2019-03-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20190321_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
