# Generated by Django 2.1.7 on 2019-05-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20190403_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('not_visible', 'not_visible'), ('catalog', 'catalog'), ('search', 'search'), ('all', 'all')], default='all', max_length=32),
        ),
    ]
