# Generated by Django 2.0.6 on 2018-09-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdjango', '0004_auto_20180921_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='current_version',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='current_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
