# Generated by Django 2.1.4 on 2019-01-29 02:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190129_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_data',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
    ]
