# Generated by Django 2.0.6 on 2018-11-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180914_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'permissions': (('list_user', 'Can list users'),)},
        ),
    ]
