# Generated by Django 2.0.6 on 2018-09-17 14:11

from django.db import migrations


def add_data(apps, schema_editor):
	from django.contrib.auth.models import Permission
	from django.contrib.contenttypes.models import ContentType

	contentType = ContentType.objects.get(model='group');
	Permission.objects.create(name="Can list Group", content_type=contentType, codename="list_group");


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180914_1709'),
    ]

    operations = [
    	migrations.RunPython(add_data),
    ]
