# Generated by Django 2.0.6 on 2018-07-26 15:05

from django.db import migrations
import djongo.models.fields
import webdjangular.apps.blog.models.Tag


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=djongo.models.fields.ArrayModelField(model_container=webdjangular.apps.blog.models.Tag.Tag, null=True),
        ),
    ]
