# Generated by Django 2.0.6 on 2018-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180904_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
