# Generated by Django 2.0.6 on 2018-09-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180914_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('list_user', 'Can list users'),)},
        ),
    ]
